(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



TransRot[theta_,d_,a_,alpha_]:={{Cos[theta],-Cos[alpha]*Sin[theta],Sin[alpha]*Sin[theta],a*Cos[theta]},{Sin[theta],Cos[alpha]*Cos[theta],-Sin[alpha]*Cos[theta],a*Sin[theta]},{0,Sin[alpha],Cos[alpha],d},{0,0,0,1}};
H={
 {1, 0, 0, 0},
 {0, 1, 0, 0},
 {0, 0, 1, 0}
};
Subscript[T, 0]={
 {1, 0, 0, 0},
 {0, 1, 0, 0},
 {0, 0, 1, 0},
 {0, 0, 0, 1}
};T2R[T_]:=H.T.Transpose[H];



